# vars
general {
    allow_tearing = true
}

xwayland {
    force_zero_scaling = true
}

misc {
    vfr = true
}

env = WLR_DRM_NO_ATOMIC, 1

# display layout
# laptop mon
monitor = eDP-1, highrr, 0x0, 1
# DELL S2522HG
monitor = DP-3, highrr, 0x0, 1
