# vars
general {
    sensitivity = 1
    cursor_inactive_timeout = 10
    no_cursor_warps = false
    apply_sens_to_raw = false
    resize_on_border = false
}

input {
    kb_layout = us
    accel_profile = flat
    follow_mouse = 1
    mouse_refocus = false
    touchpad {
        natural_scroll = true
    }
}

# fcitx
env = INPUT_METHOD, fcitx
env = GTK_IM_MODULE, fcitx
env = QT_IM_MODULE, fcitx
env = XMODIFIERS. @im=fcitx

# per-device settings

## thinkpad trackpad
#device:syna8004:00-06cb:cd8b-mouse {
#    sensitivity = 0.2
#}
#device:syna8004:00-06cb:cd8b-touchpad {
#    sensitivity = 0.2
#}
#device:tpps/2-elan-trackpoint {
#    sensitivity = 0.2
#}
