# window management
$mod = SUPER
$mod_alt = SUPER SHIFT
$mod_alt_alt = SUPER CONTROL

bind = $mod, Q, killactive,
bind = $mod, C, exit
bind = $mod, F, togglefloating
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod_alt, H, movewindow, l
bind = $mod_alt, L, movewindow, r
bind = $mod_alt, J, movewindow, d
bind = $mod_alt, K, movewindow, u
bind = $mod, M, fullscreen, 0 
bind = $mod_alt, M, fakefullscreen
bind = $mod, T, execr, hyprctl keyword general:layout master
bind = $mod_alt, T, execr, hyprctl keyword general:layout dwindle

## dwindle specific

## master specific
bind = $mod, Return, layoutmsg, swapwithmaster auto
bind = $mod_alt_alt, H, splitratio, -0.05
bind = $mod_alt_alt, J, layoutmsg, rollprev
bind = $mod_alt_alt, K, layoutmsg, rollnext
bind = $mod_alt_alt, L, splitratio, +0.05 

## mouse resize
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

## change tab
bind = $mod, 1,   workspace, 1
bind = $mod, 2,   workspace, 2
bind = $mod, 3,   workspace, 3
bind = $mod, 4,   workspace, 4
bind = $mod, 5,   workspace, 5
bind = $mod, 6,   workspace, 6
bind = $mod, 7,   workspace, 7
bind = $mod, 8,   workspace, 8
bind = $mod, 9,   workspace, 9
bind = $mod, 0,   togglespecialworkspace, =
bind = $mod, Tab, workspace, previous

## move app to tab
bind = $mod_alt, 1, movetoworkspacesilent, 1
bind = $mod_alt, 2, movetoworkspacesilent, 2
bind = $mod_alt, 3, movetoworkspacesilent, 3
bind = $mod_alt, 4, movetoworkspacesilent, 4
bind = $mod_alt, 5, movetoworkspacesilent, 5
bind = $mod_alt, 6, movetoworkspacesilent, 6
bind = $mod_alt, 7, movetoworkspacesilent, 7
bind = $mod_alt, 8, movetoworkspacesilent, 8
bind = $mod_alt, 9, movetoworkspacesilent, 9
bind = $mod_alt, 0, movetoworkspacesilent, special:=

## changemon
bind = $mod, comma, focusmonitor, -1
bind = $mod, period, focusmonitor, +1
bind = $mod_alt, comma, movewindow, -1
bind = $mod_alt, period, movewindow, +1
bind = $mod_alt CONTROL, comma, moveworkspacetomonitor, -1
bind = $mod_alt CONTROL, period, moveworkspacetomonitor, +1

# applications
$term        = alacritty
$browser     = firefox
$games       = steam
$messenger   = flatpak run im.riot.Riot
$editor      = emacsclient --create-frame
$filemanager = thunar
$launch1     = tofi-run | xargs hyprctl dispatch exec --
$launch2     = tofi-drun | xargs hyprctl dispatch exec --

bind = $mod_alt, Return, exec, $term
bind = $mod_alt, F, exec, $browser
bind = $mod_alt, R, exec, [workspace 9 silent noanim] $games
bind = $mod_alt, D, exec, [workspace 8 silent noanim] $messenger
bind = $mod_alt, E, exec, $editor
bind = $mod_alt, G, exec, $filemanager
bind = $mod_alt, P, exec, $launch2
bind = $mod,  P, exec, $launch1

## screenshot
$screenshot_full = flameshot gui
$screenshot_crop = flameshot full

bind = $mod_alt,         S, exec, $screenshot_crop
bind = $mod_alt_alt, S, exec, $screenshot_full

## media keys
$mediaplayer    = $term -e ~/.config/ncmpcpp/ncmpcpp.sh
$medianext      = mpc next
$mediaprev      = mpc prev
$mediaup        = mpc volume +5
$mediadown      = mpc volume -5
$mediaplaypause = mpc toggle

bind = , XF86AudioMute,        exec, $mediaplayer
bind = , XF86AudioNext,        exec, $medianext
bind = , XF86AudioPrev,        exec, $mediaprev
bind = , XF86AudioPlay,        exec, $mediaplaypause
bind = , XF86AudioRaiseVolume, exec, $mediaup
bind = , XF86AudioLowerVolume, exec, $mediadown

## brightness
$brightnessup   = light -T 1.15 && light -A 3%
$brightnessdown = light -T 0.85 && light -U 3%

bind = , XF86MonBrightnessUp,   exec, $brightnessup
bind = , XF86MonBrightnessDown, exec, $brightnessdown

## lock/sleep
$lock  = ~/.config/hypr/scripts/lock.sh
$sleep = loginctl suspend

bind = $mod,  Delete, exec, $lock
bind = $mod_alt, Delete, exec, $lock & sleep 2; $sleep
