# vars
general {
    layout = master
}

master {
    mfact = 0.55
    new_is_master = true
    inherit_fullscreen = true
    smart_resizing = false
    drop_at_cursor = true
    new_on_top = true
}

# disable window decoration
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
