# disable anim on layers
layerrule = noanim, .*

# popups no longer disappear
windowrulev2 = float, title:^(waybar)$, class:^(waybar)$
windowrulev2 = minsize 1 1, title:^(waybar)$, class:^(waybar)$
windowrulev2 = move onscreen 100% 16px, title:^(waybar)$, class:^(waybar)$

windowrulev2 = float, title:^()$, class:^(steam)$
windowrulev2 = stayfocused, title:^()$, class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$, class:^(steam)$
windowrulev2 = noanim, title:^()$, class:^(steam)$

# below copied from https://github.com/coffebar/dotfiles/blob/main/.config/hyprland/hyprland.conf

# firefox Picture-in-Picture
windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = pin,class:^(firefox)$,title:^(Picture-in-Picture)$
#windowrulev2 = nofullscreenrequest,class:^(firefox)$,title:^(Picture-in-Picture)$
# firefox figma micro indicator
#windowrulev2 = nofullscreenrequest,class:^(firefox)$,title:^(Firefox — Sharing Indicator)$
windowrulev2 = float,class:^(firefox)$,title:^(Firefox — Sharing Indicator)$

# archive popups
windowrulev2 = float,class:^(file-roller)$
windowrulev2 = center,class:^(file-roller)$
windowrulev2 = float,class:^(xarchiver)$
windowrulev2 = center,class:^(xarchiver)$

# common modals
windowrule = float,title:^(Open)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$
windowrulev2 = float,title:^(Create a new archive)$
windowrulev2 = center,title:^(Create a new archive)$

# pavucontrol
windowrule = center,pavucontrol
windowrule = float,pavucontrol
