# define colours
$coltext      = 0xffd8ded3
$colfg        = 0xff4c5844
$colbg        = 0xff3e4637
$colfocus     = 0xff808080
$colunfocus   = 0xff282e22
$colhighlight = 0xffc4b550

# vars
general {
    border_size = 1
    gaps_in = 0
    gaps_out = 0
    col.inactive_border = $colunfocus
    col.active_border = $colfocus
    col.nogroup_border_active = $colfocus $colhighlight
    col.nogroup_border = $colunfocus $colhighlight
}

decoration {
    rounding = 0
    drop_shadow = 0
    dim_inactive = true
    dim_strength = 0.05
    dim_special = 0.2
    
    blur {
        enabled = false
    }    
}

animations {
    enabled = false
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    background_color = $colbg
}

# anim speed
animation=windows, 1, 2, default
animation=workspaces, 0
animation=specialWorkspace, 1, 2, default

# themes
env = QT_QPA_PLATFORMTHEME, qt5ct
env = XCURSOR_SIZE, 24
