progressbar_look = "   "
header_visibility = "no"
statusbar_visibility = "no"
visualizer_data_source = /tmp/mpd.fifo
visualizer_output_name = 'Visualizer'

visualizer_in_stereo = no
visualizer_type = spectrum
visualizer_fps = 30
visualizer_autoscale = yes
visualizer_color = yellow
visualizer_spectrum_smooth_look = yes

## A value between 1 and 5 inclusive. Specifying a larger value makes the
## visualizer look at a larger slice of time, which results in less jumpy
## visualizer output.
visualizer_spectrum_dft_size = 3
visualizer_spectrum_gain = 10

## Left-most frequency of visualizer in Hz, must be less than HZ MAX
visualizer_spectrum_hz_min = 20
## Right-most frequency of visualizer in Hz, must be greater than HZ MIN
visualizer_spectrum_hz_max = 10000
